FROM golang:latest AS builder

RUN CGO_ENABLED=0 go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder /go/bin/goose /usr/local/bin/goose

WORKDIR /migrations

ENTRYPOINT ["goose"]
