[program:nutrifood-celery-worker]
directory=__PROJECT_PATH__
command=__VENV_PATH__/bin/celery -A backend.config.celery_app:app worker --loglevel=INFO --queues=default,periodic
user=__APP_USER__
autostart=true
autorestart=true
startsecs=5
startretries=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/nutrifood-celery-worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
environment=PYTHONUNBUFFERED="1",PYTHONDONTWRITEBYTECODE="1",LOG_COMPONENT="celery-worker"
